"""
"""
VERSION = "1.6_dev"

CANVAS_WIDTH = 800
CANVAS_HEIGHT = 600
CANVAS_CENTER_X = CANVAS_WIDTH / 2
CANVAS_CENTER_Y = CANVAS_HEIGHT / 2
CANVAS_CENTER = (CANVAS_CENTER_X, CANVAS_CENTER_Y)
TRENCH_LENGTH_M = 3500
TRENCH_WIDTH_M = 10
TRENCH_HEIGHT_M = 10
TRENCH_WALL_INTERVAL_M = 20
TRENCH_COLOUR = "#ddd"
EXHAUST_PORT_POSITION_M = TRENCH_LENGTH_M - 100
EXHAUST_PORT_WIDTH_M = TRENCH_WIDTH_M / 3.0
PROTON_TORPEDO_RANGE_M = 200
PROTON_TORPEDO_RADIUS_M = 0.3
PROTON_TORPEDO_SPAN_M = 0.7
LAUNCH_POSITION_M = EXHAUST_PORT_POSITION_M - PROTON_TORPEDO_RANGE_M
DISTANCE_COLOUR = "Red"
DEATH_STAR_RADIUS = CANVAS_HEIGHT * 0.4
DEATH_STAR_COLOUR = "#aaa"
LINE_WIDTH = 2

MODE_INTRO = 0
MODE_GAME = 1
MODE_VICTORY = 2

SHIP_WIDTH_M = 1.6
SHIP_HEIGHT_M = 0.8

NEAR_PLANE_M = 0.1
FAR_PLANE_M = 180.0
SCALE_WIDTH = CANVAS_WIDTH / 2
SCALE_HEIGHT = CANVAS_HEIGHT / 2

FORWARD_VELOCITY_MS = 60.0
PROTON_TORPEDO_VELOCITY_MS = FORWARD_VELOCITY_MS * 1.1
VELOCITY_MAX_MS = 15.0
VELOCITY_DAMPEN = 0.7
ACCELERATION_MSS = 100.0


TORPEDO_COLOUR = "Red"
EXHAUST_PORT_COLOUR = "Red"
INTRO_TEXT_COLOUR = "Yellow"
WARNING_TEXT_COLOUR = "Red"
PARTICLE_COLOUR = "White"
FONT_STYLE = "sans-serif"

BARRIER_COLOURS = ((255, 0, 0), (255, 192, 0), (0, 255, 0), (255, 255, 0), (0, 255, 255), (255, 0, 255))

BLOCK_VERTEX = ((0, 1), (1, 2), (2, 3), (3, 0), (0, 4), (1, 5), (2, 6), (3, 7), (4, 5), (5, 6), (6, 7), (7, 4), (0, 2), (1, 3))

HEX_DIGITS = ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f')
