[project]
name = "TrenchRun"
version = "1.6"
authors = [
    {name = "RPINerd", email = "RPINerd@gmail.com"}
]
description = "A remake of the trench sequence of the 1983 Star Wars arcade cabinet."
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.2.0",
    "pygame-ce>=2.5.8",
]

[project.scripts]
trenchrun = "trenchrun.main:main"

[project.urls]
homepage = "https://github.com/RPINerd/TrenchRun"
issues = "https://github.com/RPINerd/TrenchRun/issues"
